
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

VERSION="2.0.0"

ACCOUNTS=["GAG2V5QGHSQNO6XJBVNZ2GD5H6TW72LZP77225YZUN3AMRJBJ5RLUFCA"]

[DOCUMENTATION]

ORG_NAME="Smiley"

ORG_LOGO="https://smileycoin5.files.wordpress.com/2022/12/f42f364c-d16d-4ecc-9ec0-e37182abb9bd.png"

[[CURRENCIES]]

code="Smile"

issuer="GAG2V5QGHSQNO6XJBVNZ2GD5H6TW72LZP77225YZUN3AMRJBJ5RLUFCA"

display_decimals=0

name="Smile"

desc="making people smile"

image="https://smileycoin5.files.wordpress.com/2022/12/f42f364c-d16d-4ecc-9ec0-e37182abb9bd.png"

